name: Release Version

# 1
on:
  # 2
  push:
  pull_request:

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.12"
          channel: 'stable'
          cache: true
      # 12
      - name: Get dependencies
        run:  flutter pub get

      # Runs a set of commands using the runners shell
      - name: Build
        run: flutter build appbundle
      
      - name: Test
        run: flutter test --coverage

      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1 
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: coverage/lcov.info